name: stacked_mvvm
description: MVVM architecture implementation
version: 0.2.2
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  equatable: ^2.0.5
  stacked: ^3.4.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
