name: remedi_analytics
description: A new Flutter package.
version: 0.2.0
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
